In [1]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  
from sklearn.neural_network import MLPClassifier 
from sklearn.preprocessing import StandardScaler  
from sklearn.tree import DecisionTreeClassifier  
%matplotlib inline

In [13]:
# Load dataset
data = pd.read_csv(r"C:\Users\prana\Downloads\drugdataset.csv")
data.head()


Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  drugY
1   47    0   1            1   13.093  drugC
2   47    0   1            1   10.114  drugC
3   28    1   0            1    7.798  drugX
4   61    1   1            1   18.043  drugY

In [14]:
data.describe()

Age         Sex          BP  Cholesterol     Na_to_K
count  200.000000  200.000000  200.000000   200.000000  200.000000
mean    44.315000    0.480000    1.090000     0.515000   16.084485
std     16.544315    0.500854    0.821752     0.501029    7.223956
min     15.000000    0.000000    0.000000     0.000000    6.269000
25%     31.000000    0.000000    0.000000     0.000000   10.445500
50%     45.000000    0.000000    1.000000     1.000000   13.936500
75%     58.000000    1.000000    2.000000     1.000000   19.380000
max     74.000000    1.000000    2.000000     1.000000   38.247000

In [8]:
data.Drug.unique()


array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [9]:
x = data.drop('Drug',axis=1).to_numpy()
y = data['Drug'].to_numpy()

#Create Train and Test datasets
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y,test_size = 0.20,random_state=100)

#Scale the data
sc = StandardScaler()  
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [10]:
mlp = MLPClassifier(hidden_layer_sizes=(5,4,5), activation='relu',solver='adam', max_iter=10000,random_state=100)  
mlp.fit(x_train2, y_train) 
predictions = mlp.predict(x_test2) 

#Evaluation Report and Matrix
from sklearn.metrics import classification_report, confusion_matrix  
target_names=['drugY','drugX','drugC','drugB','drugA']
print("Neural Network - Confusion Matrix")  
print(confusion_matrix(y_test,predictions))  
print("Neural Network - Classification Report") 
print(classification_report(y_test,predictions,target_names=target_names)) 

Neural Network - Confusion Matrix
[[ 5  0  0  0  0]
 [ 0  2  0  0  1]
 [ 0  0  3  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  1 17]]
Neural Network - Classification Report
              precision    recall  f1-score   support

       drugY       1.00      1.00      1.00         5
       drugX       1.00      0.67      0.80         3
       drugC       1.00      1.00      1.00         3
       drugB       0.92      1.00      0.96        11
       drugA       0.94      0.94      0.94        18

    accuracy                           0.95        40
   macro avg       0.97      0.92      0.94        40
weighted avg       0.95      0.95      0.95        40



In [11]:
for name,method in [('DT', DecisionTreeClassifier(random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['drugY','drugX','drugC','drugB','drugA']
    print('\nEstimator: {}'.format(name)) 
    print("Decision Tree - Confusion Matrix")  
    print(confusion_matrix(y_test,predict))  
    print("Classification Report") 
    print(classification_report(y_test,predict,target_names=target_names))     


Estimator: DT
Decision Tree - Confusion Matrix
[[ 4  1  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 10  1]
 [ 0  0  0  0 18]]
Classification Report
              precision    recall  f1-score   support

       drugY       1.00      0.80      0.89         5
       drugX       0.75      1.00      0.86         3
       drugC       1.00      1.00      1.00         3
       drugB       1.00      0.91      0.95        11
       drugA       0.95      1.00      0.97        18

    accuracy                           0.95        40
   macro avg       0.94      0.94      0.93        40
weighted avg       0.96      0.95      0.95        40

